[features]
seeds = false
[programs.localnet]
fibonacci = "7XMEmVc873gosEt5XAha2X7oPtVqb5K68xpGSwtCx6AQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
